### ISSUE TITLE
Interview submission pipeline

### ISSUE THREAD

**Issue by timothyachumba** [timothyachumba/theloversmag#1]
We want to make it really easy for others to upload their own interviews to the site through a submission form.

Here is a workflow. https://getkirby.com/docs/cookbook/forms/creating-pages-from-frontend

**Comment by williamchanner** [comment]
**Bio**
Full name: 
Company: 
Bio:
Twitter: 

**Questions** 
What led you into design? 
What does a typical day look like? 
What’s your workstation setup? 
-      Company office
-      Workstation
-      Mac dock 
-      Mobile home screen
Where do you go to get inspired? 
What product have you recently seen that made you think this is a great design? 
What pieces of work are you most proud of?
What design challenges do you face at your company?
What music do you listen to whilst designing?
Any advice for ambitious designers? 
Anything you want to promote or plug?
